### ISSUE TITLE
ImplicitClient with AllowClientCredentials 

### ISSUE THREAD

**Issue by Condor2708** [jageall/IdentityServer.v3.MongoDb#39]
It is failing  serializing the Token when the subject its a null when RequestClientCredentials
Thanks

**Comment by jageall** [comment]
I have only been able to reproduce this with when the client configuration token type reference. Are you able to confirm this, and also the versions you are using?

Stack trace: 

at MongoDB.Bson.BsonDocument.set_Item(String name, BsonValue value)
  at IdentityServer.Core.MongoDb.TokenSerializer.Serialize(String key, Token token)
  at IdentityServer.Core.MongoDb.TokenHandleStore.<StoreAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
  at Thinktecture.IdentityServer.Core.Services.Default.DefaultTokenService.<CreateSecurityTokenAsync>d__c.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\Services\Default\DefaultTokenService.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
  at Thinktecture.IdentityServer.Core.ResponseHandling.TokenResponseGenerator.<CreateAccessTokenAsync>d__26.MoveNext() in c:\ballen\github\identity\IdSrv3\IdentityServer3\source\Core\ResponseHandling\TokenResponseGenerator.cs:line 207

{"Value cannot be null.\r\nParameter name: value"}

**Comment by Condor2708** [comment]
Yes the same issue using reference tokens... I am using the master branch with IdentityServer3 rc3.. Tha ks

**Comment by jageall** [comment]
Should be fixed with the latest nuget packages

**Comment by jageall** [comment]
@Condor2708 Could you confirm and close if the new packages fixed this for you please. If I don't hear anything further I will close this issue on 2015-08-07

**Comment by Condor2708** [comment]
Working fine thanks
